### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zachthedev** [Legoman99573/Buildtools-Updater#2]
Would you consider this tool to be good enough to use? And could you explain how to update the build tools? I am planning on using this to update my server to keep spigot up to date. Is this tool the best thing to use for that purpose? Thanks for your time!

**Comment by Legoman99573** [comment]
This is in beta, but I will try to finish up code to get some commands functional.

**Comment by Legoman99573** [comment]
Plus, buildtools will be using lastBuild, and buildtools will be placed in dependency folder to keep it clean.

**Comment by Legoman99573** [comment]
Sorry for mess. Getting use to GitHub.

**Comment by Zangoran** [comment]
So are you saying that I shouldn't use this to auto update my spigot server?

**Comment by zachthedev** [comment]
@Legoman99573 So are you saying that I shouldn't use this to auto update my spigot server?

**Comment by Legoman99573** [comment]
I am getting update prepared to fix bugs. Use the wiki one for now ;)

**Comment by Legoman99573** [comment]
Opened again so I may close when updated. There is a bug where buildtools doesn't go in dependency folder, but I may have to make a workaround batch file. But i am close to finishing, just testing it out ;)

**Comment by Legoman99573** [comment]
Ok it should be ready to go but there is a bug where buildtools files will extract in startup folder

**Comment by zachthedev** [comment]
@Legoman99573 Where is the startup folder located?

**Comment by Legoman99573** [comment]
file can be stored anywhere. Startup is buildtools.bat. Buildtools files extracting in directory where buildtools.bat is located is fixed. May wanna update script
