### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by zachthedev** [Legoman99573/Buildtools-Updater#4]
When running BuildTools.bat and after putting in Y for the continue, it crashes with the error "\Buildtools-Updater-master\files\checker.bat was unexpected at this time."

You might want to look into that.

**Comment by Legoman99573** [comment]
If it exists, it shouldnt die, but ill look into it

**Comment by Legoman99573** [comment]
May wanna redownload buildtools.bat. it should generates "files" directory. I forgot to add it back in after testing. Let me know if it continues.
In full release, checker.bat will be an updater as well, but thanks for your report. Version is same still.
