### ISSUE TITLE
Isn't it a bit long?

### ISSUE THREAD

**Issue by NatoBoram** [Legoman99573/Buildtools-Updater#7]
I did the exact same thing as this. Like I swear. And I don't really need all of this. You probably want this Updater to be universal and I admire this, but maybe you went a bit too far. Let me show you what I've done.
### BuildTools.sh

```
powershell -command Invoke-WebRequest -Uri https://hub.spigotmc.org/jenkins/job/BuildTools/lastBuild/artifact/target/BuildTools.jar -OutFile BuildTools.jar
java -jar BuildTools.jar --rev latest
```

The only flaw of my method is probably the use of PowerShell.

After that, maybe I didn't understand at all what you tried to do, which is also possible. Anyway best of luck!

**Comment by Legoman99573** [comment]
It allows updating/running of buildtools with other options like bungee update, and future added copy&paste of spigot

**Comment by NatoBoram** [comment]
Oh, that's why :+1: I'll try to do something on my fork!
